### PR TITLE
unit tests for ComputerBarStartTimestamps() #979

### PR DESCRIPTION
**Pull request by Nitesh703**

### CODE REVIEW

**Comment by Nitesh703** [comment]
Hello @samarth9008 ,
in my previous PR (which I deleted), AWS credentials were not setup because I pushed changes to my own forked repo. Now it didn't fail at Configure AWS Credentials. Now it failed at Run Fast Tests.

**Comment by Nitesh703** [comment]
I'm debugging Run Fast Tests.

**Comment by Nitesh703** [comment]
Hello @samarth9008 ,
my unit tests are failing in the CI env, it throws an assertion error: ArrowInvalid not raised. can you have a look at the tests & tell me what am I doing wrong.

**Comment by samarth9008** [comment]
The first error is reasonable, its the problem on our side

but this test is written by you and it is failing

```
core/finance/test/test_prediction_processing.py::TestComputeBarStartTimestamps::test3
```


Also make sure it follows our coding style as mentioned in the coding style doc and you can also take a look at other code in the repo to get an idea

**Comment by Nitesh703** [comment]
Hello @samarth9008 , 
I'm unable to push changes the PR, has my permissions been revoked?

**Comment by samarth9008** [comment]
> Hello @samarth9008 , I'm unable to push changes the PR, has my permissions been revoked?

No. Whats the error you are getting?

**Comment by Nitesh703** [comment]
```
(base) Nitteshs-Air:kaizenflow nitteshkataria$ git push origin UnitTests_ComputeBarStartTimestamps
remote: Permission to kaizen-ai/kaizenflow.git denied to Nitesh703.
```
this is the error.

**Comment by samarth9008** [comment]
image


You have the access.

**Comment by Nitesh703** [comment]
Ok. I'm looking into this.

**Comment by Nitesh703** [comment]
Hello @samarth9008 ,
```
collected 3097 items / 2 errors / 306 deselected / 2791 selected               
==================================== ERRORS ====================================
_______________ ERROR collecting build/lib/helpers/hsql_test.py ________________
import file mismatch:
imported module 'helpers.hsql_test' has this __file__ attribute:
  /app/helpers/hsql_test.py
which is not the same as the test file we want to collect:
  /app/build/lib/helpers/hsql_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_______________ ERROR collecting build/lib/helpers/hunit_test.py _______________
import file mismatch:
imported module 'helpers.hunit_test' has this __file__ attribute:
  /app/helpers/hunit_test.py
which is not the same as the test file we want to collect:
  /app/build/lib/helpers/hunit_test.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR build/lib/helpers/hsql_test.py
ERROR build/lib/helpers/hunit_test.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
====================== 306 deselected, 2 errors in 12.87s ======================
15:05:50 - INFO  hcache.py clear_global_cache:294                       Before clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=64.0 KB
15:05:50 - WARN  hcache.py clear_global_cache:295                       Resetting 'global mem' cache '/mnt/tmpfs/tmp.cache.mem'
15:05:50 - WARN  hcache.py clear_global_cache:305                       Destroying '/mnt/tmpfs/tmp.cache.mem' ...
15:05:50 - INFO  hcache.py clear_global_cache:321                       After clear_global_cache: 'global mem' cache: path='/mnt/tmpfs/tmp.cache.mem', size=nan
ERROR: 2
Error: Process completed with exit code [2](https://github.com/kaizen-ai/kaizenflow/actions/runs/9196960419/job/25296297077#step:20:2).
```
did you have a look at this error?

**Comment by Nitesh703** [comment]
@samarth9008 
I've created a new pull request ( #1009 ) & closing this one.

**Pull request closed without merging**
