### PR TITLE
Issue-785 Draft code for unit tests of normalize function

### PR DESCRIPTION
**Pull request by aish-nidhi**
[Issue- #785](https://github.com/kaizen-ai/kaizenflow/issues/785)

Unit tests for `normalize()` function :- 

- [x] Test with simple signal input data
- [x] Test with NaN value in the signal input data

### CODE REVIEW

**Comment by aish-nidhi** [comment]
This is a draft PR.

**Comment by aish-nidhi** [comment]
Both tests are passing and linter has been run on file.

image

**Review by gpsaggese — COMMENTED** [review]
LGTM

**Review by DanilYachmenev — COMMENTED** [review]
lgtm

**Review by DanilYachmenev — APPROVED** [review]

**Pull request merged**
